// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	startup "metaLand/app/api/internal/handler/startup"
	"metaLand/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {


	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OIDCAuthMiddleware},
			[]rest.Route{
				{
					// 查询项目列表
					Method:  http.MethodGet,
					Path:    "/startups",
					Handler: startup.ListStartupsHandler(serverCtx),
				},
				{
					// 创建
					Method:  http.MethodPost,
					Path:    "/startups",
					Handler: startup.CreateStartupsHandler(serverCtx),
				},
				{
					// 判断项目是否存在
					Method:  http.MethodGet,
					Path:    "/check-exists",
					Handler: startup.CheckStartupExistsHandler(serverCtx),
				},
				{
					// 获取信息通过ID
					Method:  http.MethodGet,
					Path:    "/getInfo/:startupId([0-9]+)",  // 直接在路径中嵌入正则表达式，限制startupId为数字
					Handler: startup.GetStartupInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/startup"),
	)

}
