// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	startup "metaLand/app/api/internal/handler/startup"
	"metaLand/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OIDCAuthMiddleware},
			[]rest.Route{
				{
					// 查询项目列表
					Method:  http.MethodGet,
					Path:    "/startups",
					Handler: startup.ListStartupsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/startup"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OIDCAuthMiddleware},
			[]rest.Route{
				{
					// 判断项目是否存在
					Method:  http.MethodGet,
					Path:    "/check-exists",
					Handler: startup.CheckStartupExistsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/startup"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OIDCAuthMiddleware},
			[]rest.Route{
				{
					// 获取项目详情
					Method:  http.MethodGet,
					Path:    "/getInfo",
					Handler: startup.GetStartupInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/startup"),
	)
}
