// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CheckStartupExistsRequest struct {
	Name                 string `json:"name,omitempty"`                   // 项目名称（可选，与合约地址至少传一个）
	TokenContractAddress string `json:"token_contract_address,omitempty"` // 代币合约地址（可选，与名称至少传一个）
	IsDeleted            bool   `json:"is_deleted,omitempty"`             // 是否包含已删除记录（默认：false）
}

type CheckStartupExistsResponse struct {
	Exists bool `json:"exists"` // 是否存在
}

type FollowRelation struct {
	ComerID uint64 `json:comerID`
}

type GetStartupInfoRequest struct {
	StartupId uint64 `form:"startupId"`
}

type Startup struct {
	ComerID              uint64 `json:"comerID" db:"comer_id"`
	Name                 string `json:"name" db:"name"`
	Mode                 uint8  `json:"mode" db:"mode"`
	Logo                 string `json:"logo" db:"logo"`
	Cover                string `json:"cover" db:"cover"`
	Mission              string `json:"mission" db:"mission"`
	TokenContractAddress string `json:"tokenContractAddress" db:"token_contract_address"`
	Overview             string `json:"overview" db:"overview"`
	ChainID              uint64 `json:"chainID" db:"chain_id"`
	TxHash               string `json:"blockChainAddress" db:"tx_hash"`
	OnChain              bool   `json:"onChain" db:"on_chain"`
	KYC                  string `json:"kyc" db:"kyc"`
	ContractAudit        string `json:"contractAudit" db:"contract_audit"`
}

type StartupInfoResponse struct {
	Code    int        `json:"code"`    // 状态码
	Message string     `json:"message"` // 消息
	Data    StartupRes `json:"data"`    // 项目详情
}

type StartupRes struct {
	ComerID              uint64 `json:"comer_id" db:"comer_id"`
	Name                 string `json:"name" db:"name"`
	Mode                 uint8  `json:"mode" db:"mode"`
	Logo                 string `json:"logo" db:"logo"`
	Cover                string `json:"cover" db:"cover"`
	Mission              string `json:"mission" db:"mission"`
	TokenContractAddress string `json:"token_contract_address" db:"token_contract_address"`
	Overview             string `json:"overview" db:"overview"`
	TxHash               string `json:"tx_hash" db:"tx_hash"`
	OnChain              bool   `json:"on_chain" db:"on_chain"`
	KYC                  string `json:"kyc" db:"kyc"`
	ContractAudit        string `json:"contract_audit" db:"contract_audit"`
	Website              string `json:"website" db:"website"`
	Discord              string `json:"discord" db:"discord"`
	Twitter              string `json:"twitter" db:"twitter"`
	Telegram             string `json:"telegram" db:"telegram"`
	Docs                 string `json:"docs" db:"docs"`
	Email                string `json:"email" db:"email"`
	Facebook             string `json:"facebook" db:"facebook"`
	Medium               string `json:"medium" db:"medium"`
	Linktree             string `json:"linktree" db:"linktree"`
	LaunchNetwork        int    `json:"launch_network" db:"launch_network"`
	TokenName            string `json:"token_name" db:"token_name"`
	TokenSymbol          string `json:"token_symbol" db:"token_symbol"`
	TotalSupply          int64  `json:"total_supply" db:"total_supply"`
	PresaleStart         string `json:"presale_start" db:"presale_start"` // RFC3339格式时间字符串
	PresaleEnd           string `json:"presale_end" db:"presale_end"`     // RFC3339格式时间字符串
	LaunchDate           string `json:"launch_date" db:"launch_date"`     // RFC3339格式时间字符串
	TabSequence          string `json:"tab_sequence" db:"tab_sequence"`
	IsDeleted            bool   `json:"is_deleted" db:"is_deleted"`
	CreatedAt            string `json:"created_at" db:"created_at"` // RFC3339格式时间字符串
	UpdatedAt            string `json:"updated_at" db:"updated_at"` // RFC3339格式时间字符串
}

type StartupTeamMember struct {
	ComerID      uint64 `json:"comerID"`
	StartupID    uint64 `json:"startupID"`
	Position     string `json:"position"`
	Comer        string `json:"comer"`
	FollowedByMe bool   `json:"followedByMe"`
}

type Tag struct {
	Name     string `json:"name"`
	Category string `json:"category"`
	IsIndex  bool   `json:"isIndex"`
}

type Wallet struct {
	Address string `json:address`
}
